version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestPSURgitProject
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
services:
- serviceName: project.testpsurgit.integrations:testGitSave
  packages:
  - name: TestPSURgitProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
